name: MacOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up CMake
        uses: jurplel/install-cmake-actions@v2
      - name: Install dependencies
        run: |
          brew install cmake
      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make